### ISSUE TITLE
Default firewall install with attribute allowing SSH to work fails on CentOS 7

### ISSUE THREAD

**Issue by jasonmcintosh** [chef-cookbooks/firewall#103]
On a clean CentOS 7.1.1503 box with nothing else applied, the firewall log shows that the rule:
```allow world to ssh```
is applied to the server.  However, it appears that the firewall is turned on and SSH is NOT allowed.  The only file I see is /etc/sysconfig/firewalld-chef.rules - the main /etc/sysconfig/firewalld has not been modified.  The output of:
```firewall-cmd --list-all```:
```
drop (default, active)
 interfaces: eno1234567
 sources:
 services:
 ports:
 masquerade: no
 forward-ports:
 icmp-blocks:
 rich-rules:
```

node attributes for firewall:
```
firewall
allow_ssh: true
allow_winrm: false
ubuntu_iptables: false
allow_established: true
ipv6_enabled: true
iptables
ufw
```
