### ISSUE TITLE
2.5.3 Attempting to install iptables-services on Amazon Linux 2016.09.0 and fails because not a valid package

### ISSUE THREAD

**Issue by LevonBecker** [chef-cookbooks/firewall#154]
### Cookbook version
2.5.3

### Chef-client version
12.15.19

### Platform Details
Cloud:                       (aws)
Platform:                   (amazon)
Platform Version:     (2016.09)

### Bootstrap Method
Test Kitchen EC2 Driver:
kitchen-ec2 (1.2.0)
test-kitchen (1.13.2)

### Scenario:
Firewall cookbook attempting to install iptables-services on Amazon Linux 2016.09.0. This is not an available package/name.

### Steps to Reproduce:
Attributes
```ruby
default['firewall']['redhat7_iptables'] = true
default['firewall']['ubuntu_iptables'] = true
default['firewall']['ipv6_enabled'] = false
```

https://github.com/bonusbits/bonusbits_base/blob/master/.kitchen.ec2.yml

**.kitchen.ec2.yml**
```yaml
driver:
  name: ec2
  associate_public_ip: <%= ENV['AWS_PUBLIC_IP'] %>
  aws_ssh_key_id: <%= ENV['AWS_SSH_KEY_ID'] %>
  security_group_ids:
    - <%= ENV['AWS_SECURITY_GROUP_1'] %>
    <%= "- " + ENV['AWS_SECURITY_GROUP_2'] if ENV['AWS_SECURITY_GROUP_2'] %>
    <%= "- " + ENV['AWS_SECURITY_GROUP_3'] if ENV['AWS_SECURITY_GROUP_3'] %>
    <%= "- " + ENV['AWS_SECURITY_GROUP_4'] if ENV['AWS_SECURITY_GROUP_4'] %>
    <%= "- " + ENV['AWS_SECURITY_GROUP_5'] if ENV['AWS_SECURITY_GROUP_5'] %>
  subnet_id: <%= ENV['AWS_SUBNET'] %>
  vpc_id: <%= ENV['AWS_VPC_ID'] %>
  iam_profile_name: <%= ENV['AWS_IAM_INSTANCE_PROFILE'] %>
  region: <%= ENV['AWS_REGION'] %>
  instance_type: t2.micro

provisioner:
  name: chef_zero
  require_chef_omnibus: 12.15.19
  driver_config:
    ssl_verify_mode: ":verify_none"
  data_bags_path: "test/data_bags"
  encrypted_data_bag_secret_key_path: "test/data_bags/encrypted_data_bag_secret"
  roles_path: "test/roles"
  environments_path: "test/environments"

platforms:
  - name: amzn-2016-latest
    driver:
      image_search:
        owner-id: 137112412989
        name: amzn-ami-hvm-2016.*x86_64-gp2
      tags:
        Name: kitchen-bonusbits-base-amzn-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        Owner: <%= ENV['USER'] %>
    transport:
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: rhel-6
    driver:
      instance_type: t2.micro
      tags:
        Name: kitchen-bonusbits-base-rhel6-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: rhel-7
    driver:
      instance_type: t2.micro
      tags:
        Name: kitchen-bonusbits-base-rhel7-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: ec2-user
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: ubuntu-14.04
    driver:
      instance_type: t2.micro
      tags:
        Name: kitchen-bonusbits-base-ubuntu14-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: ubuntu
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: ubuntu-15
    driver:
      instance_type: t2.micro
      tags:
        Name: kitchen-bonusbits-base-ubuntu15-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: ubuntu
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: ubuntu-16.04
    driver:
      instance_type: t2.micro
      tags:
        Name: kitchen-bonusbits-base-ubuntu16-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: ubuntu
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: windows-2008r2
    driver:
      instance_type: m3.medium
      tags:
        Name: kitchen-bonusbits-base-windows-2008r2-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: administrator
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>
  - name: windows-2012r2
    driver:
      instance_type: m3.medium
      tags:
        Name: kitchen-bonusbits-base-windows-2012r2-<%= ENV['USER'] %>
        Created-By: Test Kitchen
        OWNER: <%= ENV['USER'] %>
    transport:
      username: administrator
      ssh_key: <%= ENV['AWS_SSH_KEY_PATH'] %>

suites:
  - name: base
    run_list:
      - role[base]
    includes: ["amzn-2016-latest", "rhel-6", "rhel-7", "ubuntu-14.04", "ubuntu-16.04", "windows-2012r2"]
    provisioner:
      client_rb:
        environment: "bonusbits_base"
  - name: base_epel_repo
    run_list:
      - role[base]
    includes: ["amzn-2016-latest", "rhel-6", "rhel-7"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_epel_repo"
  - name: base_no_firewall
    run_list:
      - role[base]
    includes: ["amzn-2016-latest", "rhel-6", "rhel-7", "ubuntu-14.04", "ubuntu-16.04", "windows-2012r2"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_no_firewall"
  - name: base_no_software
    run_list:
      - role[base]
    includes: ["amzn-2016-latest", "rhel-6", "rhel-7", "ubuntu-14.04", "ubuntu-16.04", "windows-2012r2"]
    provisioner:
      client_rb:
        environment: "bonusbits_base_no_software"
```
### Expected Result:
I'm guessing this is the package it should install instead of **iptables-services**

```iptables-utils.x86_64 : iptables and ip6tables services for iptables```

### Actual Result:
```
         * firewall[default] action install
           - install iptables and enable/start services
         * yum_package[iptables] action install (up to date)
         * yum_package[iptables-ipv6] action install (up to date)
         * yum_package[iptables-services] action install
           * No candidate version available for iptables-services
           ================================================================================
           Error executing action `install` on resource 'yum_package[iptables-services]'
           ================================================================================

           Chef::Exceptions::Package
           -------------------------
           No candidate version available for iptables-services

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:78:in `run_action'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block (2 levels) in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `each'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:106:in `block in converge'
           /tmp/kitchen/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:105:in `converge'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb

            39:           package p do
            40:             action :install
            41:           end
            42:         end

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb:39:in `block (3 levels) in <class:FirewallIptables>'

           yum_package("iptables-services") do
             package_name "iptables-services"
             action [:install]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             declared_type :package
             cookbook_name "bonusbits_base"
             flush_cache {:before=>false, :after=>false}
           end

           Platform:
           ---------
           x86_64-linux

       Running handlers:
       [2016-10-31T18:50:06+00:00] ERROR: Running exception handlers
       Running handlers complete
       [2016-10-31T18:50:06+00:00] ERROR: Exception handlers complete
       Chef Client failed. 3 resources updated in 07 seconds
       [2016-10-31T18:50:06+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2016-10-31T18:50:06+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2016-10-31T18:50:06+00:00] ERROR: yum_package[iptables-services] (/tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_iptables.rb line 39) had an error: Chef::Exceptions::Package: No candidate version available for iptables-services
       [2016-10-31T18:50:06+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
```
From terminal:
```bash
$ sudo yum install iptables-services
Loaded plugins: priorities, update-motd, upgrade-helper
amzn-main/latest                                                                                                                      | 2.1 kB     00:00
amzn-updates/latest                                                                                                                   | 2.3 kB     00:00
No package iptables-services available.
Error: Nothing to do
```
