### ISSUE TITLE
Configuration rules into firewalld/centos

### ISSUE THREAD

**Issue by jeusdi** [chef-cookbooks/firewall#167]
### Cookbook version
2.6.1

### Chef-client version
12.9

### Platform Details
centos

### Scenario:
active firealld with some rules

### Steps to Reproduce:
I've created this recipe:

```
# enable platform default firewall
firewall 'default' do
  action :install
end

# open standard ssh port
firewall_rule 'ssh' do
  port     22
  command  :allow
end

# open multiple ports for http/https, note that the protocol
# attribute is required when using ports
firewall_rule 'http/https' do
  protocol :tcp
  port     [80, 443, 8080]
  command   :allow
end
```

### Expected Result:
`firewalld` is running and configured with my custom rules.

### Actual Result:
When I perform `firewall--cmd list-all` it's getting me:

```
drop (active)
  target: DROP
  icmp-block-inversion: no
  interfaces: eth0 eth1
  sources:
  services:
  ports:
  protocols:
  masquerade: no
  forward-ports:
  sourceports:
  icmp-blocks:
  rich rules:
```

I've realized that:

```
[vagrant@localhost ~]$ sudo iptables -L -n -v | grep http
   18   912 ACCEPT     tcp  --  *      *       0.0.0.0/0            0.0.0.0/0            tcp multiport dports 443,80,8080 /* http/https */
```

Any ideas?
